[toolchain]

[features]
resolution = true
skip-lint = false

[programs.Devnet]
mev_tip_distribution = "96Ct8jQauoJNxwaR9t5MwadpNCTa718Q2LA8kASXmN9R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "set -a && . ./.env && set +a && yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/mevtiptester.ts"
top-up = "yarn run ts-node scripts/top-up.ts"
initialize = "set -a && . ./.env && set +a && yarn run ts-node scripts/initialize.ts"
claim = "set -a && . ./.env && set +a && yarn run ts-node scripts/claim.ts"